version: '3.1'
services:
  database:
    container_name: skyhook-database-container
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    cap_add:
      - SYS_NICE
    env_file:
      - .env
    healthcheck:
      test: ['CMD', 'curl', '-f', 'localhost:3306']
    volumes:
      - mysql-data:/var/lib/mysql
  skyhook-server:
    container_name: skyhook-server-container
    build: .
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
volumes:
  mysql-data:
